import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Can be a telephone number, email address, website etc.
 */
export interface ContactDetail_1_0_0 {
   _$schemaId: SchemaTypes.ContactDetail_1_0_0;

  medium?: "Phone" | "Mobile phone" | "Fax" | "Email" | "Url" | "Other";
  value: string;
  comment?: string;
  [k: string]: unknown;
}
