import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Contains the '_$schemaId' attribute which is used to mark an object with a specific SchemaType.
 */
export interface SchemaId_1_0_0 {
   _$schemaId: SchemaTypes.SchemaId_1_0_0;

  _$schemaId: string;
  [k: string]: unknown;
}
