import { SchemaTypes } from "../../../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AuftragsZeile_1_0_0 {
   _$schemaId: SchemaTypes.AuftragsZeile_1_0_0;

  menge?: number;
  einheit?: string;
  gegenstand?: string;
  kostenart?: string;
  preisJeEinheit?: number;
  inklMwst?: boolean;
  [k: string]: unknown;
}
