import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Finanzierungsangaben_1_0_0 {
   _$schemaId: SchemaTypes.Finanzierungsangaben_1_0_0;

  erstellungsDatum?: {
    [k: string]: unknown;
  };
  auftragsReferenz?: {
    fakultät?: {
      name?: string;
      gebäude?: string;
      raum?: string;
      [k: string]: unknown;
    };
    angebotVom?: string;
    endsumme?: number;
    [k: string]: unknown;
  };
  finanzierung?: {
    kostenstelle?: string;
    [k: string]: unknown;
  } & Budget & {
      kostenträger?: string;
      [k: string]: unknown;
    };
  mitzeichnungIT?: {
    notwendig?: boolean;
    neinBegründung?: string;
    jaBegründung?:
      | "Grundlage ist der im Auftrag genannte IT-Vertrag"
      | "Vergleichbare Beschaffung über Rahmenvertrag möglich";
    signatur?: {
      name?: string;
      datum?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  mitzeichnungAndererOrganisationseinheiten?: {
    name?: string;
    datum?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  besteller?: {
    name?: string;
    datum?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  budgetverantwortlicher?: {
    name?: string;
    datum?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Budget {
  id?: number;
  name: string;
  [k: string]: unknown;
}
