import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Gerat_1_0_0 {
   _$schemaId: SchemaTypes.Gerat_1_0_0;

  bezeichnung?: string;
  inventarnummer?: string;
  [k: string]: unknown;
}
