import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Auftrag_1_0_0 {
   _$schemaId: SchemaTypes.Auftrag_1_0_0;

  erstellungsDatum?: {
    [k: string]: unknown;
  };
  auftragsReferenz?: {
    fakultät?: {
      name?: string;
      gebäude?: string;
      raum?: string;
      [k: string]: unknown;
    };
    angebotVom?: string;
    endsumme?: number;
    [k: string]: unknown;
  };
  bezugAufAngebot?: {
    angebotNr?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  zeilen?: {
    menge?: number;
    einheit?: string;
    gegenstand?: string;
    kostenart?: string;
    preisJeEinheit?: number;
    inklMwst?: boolean;
    [k: string]: unknown;
  }[];
  angabenZumAuftrag?: {
    vertragsende?: {
      [k: string]: unknown;
    };
    auftragsNummer?: string;
    [k: string]: unknown;
  };
  lieferanschrift?: {
    name?: string;
    vorname?: string;
    plz?: string;
    ort?: string;
    straße?: string;
    fakultätOderAbteilung?: {
      name?: string;
      gebäude?: string;
      raum?: string;
      [k: string]: unknown;
    };
    telefon?: {
      landesvorwahl?: string;
      ortsvorwahl?: string;
      anschlussNummer?: string;
      durchwahl?: string;
      [k: string]: unknown;
    };
    email?: string;
    [k: string]: unknown;
  };
  liefervermerk?: string;
  [k: string]: unknown;
}
