import { SchemaTypes } from "../../../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AuftragsReferenz_1_0_0 {
   _$schemaId: SchemaTypes.AuftragsReferenz_1_0_0;

  fakultät?: {
    name?: string;
    gebäude?: string;
    raum?: string;
    [k: string]: unknown;
  };
  angebotVom?: string;
  endsumme?: number;
  [k: string]: unknown;
}
