version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd types && rm -f package-lock.json && rm -r -f dist && npm install && npx tsc
            - run: cd log && rm -f package-lock.json && rm -r -f dist  && npm install && npx tscc
            - run: cd node-helper && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd web-helper && rm -f package-lock.json && rm -r -f dist  && npm install
            - run: cd web-helper && echo "declare module 'idtoken-verifier';" > node_modules/idtoken-verifier/build/idtoken-verifier.d.ts  && npx tsc
            - run: cd interfaces && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd tools && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd data && rm -f package-lock.json && rm -r -f dist  && npm install
            - run: cd data/src && npx prisma generate
            - run: cd data && npx tsc
            - run: cd events && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd dialog && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd agents && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd server && rm -f package-lock.json && rm -r -f dist  && npm install && npm run generate && npx tsc
            - run: cd apps/abis/server && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd apps/abis/client && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd apps/munichMotorsports/server && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd client && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc
            - run: cd client && npx browserify src/main.ts --debug -p [ tsify --noImplicitAny -p tsconfig.json ] -p browserify-derequire > dist/bundle.js
            - run: cd electron-app/app && rm -f package-lock.json && rm -r -f dist && npm install && npx ng build
            - run: cd electron-app && rm -f package-lock.json && rm -r -f dist  && npm install && npx tsc

workflows:
  build-and-test:
    jobs:
      - build-and-test
