import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Barkaufabrechnung_1_0_0 {
   _$schemaId: SchemaTypes.Barkaufabrechnung_1_0_0;

  adresse?: {
    name?: string;
    vorname?: string;
    plz?: string;
    ort?: string;
    straße?: string;
    fakultätOderAbteilung?: {
      name?: string;
      gebäude?: string;
      raum?: string;
      [k: string]: unknown;
    };
    telefon?: {
      landesvorwahl?: string;
      ortsvorwahl?: string;
      anschlussNummer?: string;
      durchwahl?: string;
      [k: string]: unknown;
    };
    email?: string;
    [k: string]: unknown;
  };
  kontoverbindung?: {
    institut?: string;
    iban?: string;
    bic?: string;
    [k: string]: unknown;
  };
  zeilen?: {
    position?: number;
    rechnungsdatum?: {
      [k: string]: unknown;
    };
    firma?: string;
    betrag?: number;
    kostenart?: string;
    dienstlicherAnlass?: string;
    artDerLeistung?: string;
    ivsNummer?: string;
    nichtErstattungsfähig?: boolean;
    [k: string]: unknown;
  }[];
  unterschriftAngabenKorrekt?: {
    name?: string;
    datum?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  bearbeitungsvermerke?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
