import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NewEntry_1_0_0 {
   _$schemaId: SchemaTypes.NewEntry_1_0_0;

  id: number;
  owner: number;
  groupId: number;
  name: string;
  data: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
