import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EditiereProjekt_1_0_0 {
   _$schemaId: SchemaTypes.EditiereProjekt_1_0_0;

  editiereProjekt?: Projekt;
  [k: string]: unknown;
}
export interface Projekt {
  id?: number;
  beginn?: string;
  ende?: string;
  name: string;
  [k: string]: unknown;
}
