import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SpeiseBudget_1_0_0 {
   _$schemaId: SchemaTypes.SpeiseBudget_1_0_0;

  quelle: Resource;
  ziel: Budget;
  wert: number;
  [k: string]: unknown;
}
export interface Resource {
  id?: number;
  name: string;
  beschreibung?: string;
  kategorie: "Geldleistung" | "Sachleistung" | "Dienstleistung";
  geldwert: number;
  [k: string]: unknown;
}
export interface Budget {
  id?: number;
  name: string;
  [k: string]: unknown;
}
