import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Adresse_1_0_0 {
   _$schemaId: SchemaTypes.Adresse_1_0_0;

  name?: string;
  vorname?: string;
  plz?: string;
  ort?: string;
  straße?: string;
  fakultätOderAbteilung?: {
    name?: string;
    gebäude?: string;
    raum?: string;
    [k: string]: unknown;
  };
  telefon?: {
    landesvorwahl?: string;
    ortsvorwahl?: string;
    anschlussNummer?: string;
    durchwahl?: string;
    [k: string]: unknown;
  };
  email?: string;
  [k: string]: unknown;
}
