import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FakultatOderAbteilung_1_0_0 {
   _$schemaId: SchemaTypes.FakultatOderAbteilung_1_0_0;

  name?: string;
  gebäude?: string;
  raum?: string;
  [k: string]: unknown;
}
