import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Kontoverbindung_1_0_0 {
   _$schemaId: SchemaTypes.Kontoverbindung_1_0_0;

  institut?: string;
  iban?: string;
  bic?: string;
  [k: string]: unknown;
}
