import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Telefonnummer_1_0_0 {
   _$schemaId: SchemaTypes.Telefonnummer_1_0_0;

  landesvorwahl?: string;
  ortsvorwahl?: string;
  anschlussNummer?: string;
  durchwahl?: string;
  [k: string]: unknown;
}
