import { SchemaTypes } from "../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Is issued as a follow-up request by the 'authenticationService' when a one time challenge should be solved before a process can be completed.
 */
export interface Challenge_1_0_0 {
   _$schemaId: SchemaTypes.Challenge_1_0_0;

  /**
   * The desired 'subject' of the jwt token (can be the ID of one of the user's agents).
   */
  sub?: string;
  code: string;
  [k: string]: unknown;
}
