import { SchemaTypes } from "../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Can be sent to the 'authenticationService' to change the password of the currently logged on user.
 */
export interface ChangePassword_1_0_0 {
   _$schemaId: SchemaTypes.ChangePassword_1_0_0;

  currentPassword: string;
  password: string;
  passwordConfirmation: string;
  [k: string]: unknown;
}
