import { SchemaTypes } from "../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Can be sent to the 'authenticationService' to login. If the login succeeds, the 'authorized' response with a 'jwt'-token will be sent as response.
 */
export interface Login_1_0_0 {
   _$schemaId: SchemaTypes.Login_1_0_0;

  email: string;
  password: string;
  sub?: string;
  [k: string]: unknown;
}
