import { SchemaTypes } from "../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Can be sent to the 'authenticationService' to reset a user's password. When the given 'email' address was correct, the user will be notified via email. This triggers a 'challenge' follow-up.
 */
export interface ResetPassword_1_0_0 {
   _$schemaId: SchemaTypes.ResetPassword_1_0_0;

  email: string;
  [k: string]: unknown;
}
