import { SchemaTypes } from "../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Is issued as a follow-up request by the 'authenticationService' when a user has entered a password-reset code and sets the new password.
 */
export interface SetPassword_1_0_0 {
   _$schemaId: SchemaTypes.SetPassword_1_0_0;

  password: string;
  passwordConfirmation: string;
  [k: string]: unknown;
}
