import { SchemaTypes } from "../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Can be sent to the 'authenticationService' to signup for a new user account.
 */
export interface Signup_1_0_0 {
   _$schemaId: SchemaTypes.Signup_1_0_0;

  timezoneOffset: number;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  passwordConfirmation: string;
  [k: string]: unknown;
}
