import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Is sent in case of an error and prompts the client to re-do its last request. The 'lastEntry' properties contains the data that failed to process
 */
export interface Retry_1_0_0 {
   _$schemaId: SchemaTypes.Retry_1_0_0;

  /**
   * The data which couldn't be processed and that should be re-sent by the client.
   */
  faultyEntry: {
    _$schemaId: string;
    [k: string]: unknown;
  };
  /**
   * The reason why the data couldn't be processed.
   */
  reason?: string;
  [k: string]: unknown;
}
