import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Is sent by a sub-process when it finished.
 */
export interface Return_1_0_0 {
   _$schemaId: SchemaTypes.Return_1_0_0;

  /**
   * Is 'true' when the sub-process ended with an error.
   */
  isError: boolean;
  /**
   * Indicates how deep the current call stack is.
   */
  returnFromLevel?: number;
  /**
   * The result of the finished sub-process. If 'isError' is 'true', this might contain the reason.
   */
  result?: {
    _$schemaId: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
