import { SchemaTypes } from "../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Is used as a result value or parameter and indicates that the parameter or return value is not used.
 */
export interface Void_1_0_0 {
   _$schemaId: SchemaTypes.Void_1_0_0;

  [k: string]: unknown;
}
