import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Lieferleistung_1_0_0 {
   _$schemaId: SchemaTypes.Lieferleistung_1_0_0;

  art?: "Neuanschaffung" | "Ersatzbeschaffung für Altgerät" | "Zubehör zum Hauptgerät";
  beschreibung?: string;
  gerät?: {
    bezeichnung?: string;
    inventarnummer?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
