import { SchemaTypes } from "../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Specifies two string fields (one for HTML and one for plaintext) which are designated for mustache email-body templates.
 */
export interface EmailTemplate_1_0_0 {
   _$schemaId: SchemaTypes.EmailTemplate_1_0_0;

  /**
   * The plain text mustache template which is used to format the subject.
   */
  subject: string;
  /**
   * The plain text mustache template which is used to generate the plaintext body of an email.
   */
  plainText: string;
  /**
   * The HTML mustache template which is used to generate the HTML body of an email.
   */
  html?: string;
  [k: string]: unknown;
}
