import { SchemaTypes } from "../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines all fields necessary to send an email.
 */
export interface TemplatedEmail_1_0_0 {
   _$schemaId: SchemaTypes.TemplatedEmail_1_0_0;

  /**
   * The sender of the email. This can be either an agent id or an actual email address
   */
  from:
    | {
        email?: string;
        [k: string]: unknown;
      }
    | {
        agentId?: number;
        [k: string]: unknown;
      };
  /**
   * The list of recipient addresses.
   */
  to: string[];
  /**
   * The list of CC recipient addresses.
   */
  cc?: string[];
  /**
   * The name of the template that should be used to generate the email.
   */
  templateName?: string;
  /**
   * Contains the data that will be fed into the template engine to create the actual email body.
   */
  data: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
