import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Verdingungsbogen_1_0_0 {
   _$schemaId: SchemaTypes.Verdingungsbogen_1_0_0;

  bezeichnungDesBeschaffungsgenstandes?: string;
  fakultätOderAbteilung?: {
    name?: string;
    gebäude?: string;
    raum?: string;
    [k: string]: unknown;
  };
  artDerLeistung?: {
    oneOf?: unknown;
    [k: string]: unknown;
  };
  vergleichsangebote?: {
    unternehmen?: string;
    angebotVom?: {
      [k: string]: unknown;
    };
    gesamtbetragInEuro?: number;
    bruttoNetto?: "brutto" | "netto";
    [k: string]: unknown;
  }[];
  vergabekriterium?: "günstigstes Angebot" | "wirtschaftlichstes Angebot" | "nur ein Anbieter";
  begründung?: string;
  [k: string]: unknown;
}
